/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

/**
 *
 * @author Chris Mazur
 */
public class GameUI extends javax.swing.JFrame {

    /**
     * Creates new form GameUI
     */
    public GameUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        currentViewPanel = new javax.swing.JPanel();
        lobbyPanel = new javax.swing.JPanel();
        radioJoinLobby1 = new javax.swing.JRadioButton();
        radioJoinLobby2 = new javax.swing.JRadioButton();
        radioJoinLobby3 = new javax.swing.JRadioButton();
        radioJoinLobby4 = new javax.swing.JRadioButton();
        radioJoinLobby5 = new javax.swing.JRadioButton();
        radioJoinLobby6 = new javax.swing.JRadioButton();
        radioJoinLobby7 = new javax.swing.JRadioButton();
        radioJoinLobby8 = new javax.swing.JRadioButton();
        joinSelectedLobbyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playersInLobby1 = new javax.swing.JLabel();
        playersInLobby2 = new javax.swing.JLabel();
        playersInLobby3 = new javax.swing.JLabel();
        playersInLobby4 = new javax.swing.JLabel();
        playersInLobby5 = new javax.swing.JLabel();
        playersInLobby6 = new javax.swing.JLabel();
        playersInLobby7 = new javax.swing.JLabel();
        playersInLobby8 = new javax.swing.JLabel();
        gameViewPanel = new javax.swing.JPanel();
        gameView1 = new client.GameView();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenuOption = new javax.swing.JMenu();
        fileNewGame = new javax.swing.JMenuItem();
        fileExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        currentViewPanel.setBackground(new java.awt.Color(200, 200, 200));

        buttonGroup1.add(radioJoinLobby1);
        radioJoinLobby1.setText("Join Lobby 1");

        buttonGroup1.add(radioJoinLobby2);
        radioJoinLobby2.setText("Join Lobby 2");

        buttonGroup1.add(radioJoinLobby3);
        radioJoinLobby3.setText("Join Lobby 3");

        buttonGroup1.add(radioJoinLobby4);
        radioJoinLobby4.setText("Join Lobby 4");

        buttonGroup1.add(radioJoinLobby5);
        radioJoinLobby5.setText("Join Lobby 5");

        buttonGroup1.add(radioJoinLobby6);
        radioJoinLobby6.setText("Join Lobby 6");

        buttonGroup1.add(radioJoinLobby7);
        radioJoinLobby7.setText("Join Lobby 7");

        buttonGroup1.add(radioJoinLobby8);
        radioJoinLobby8.setText("Join Lobby 8");

        joinSelectedLobbyButton.setText("Join Selected Lobby");
        joinSelectedLobbyButton.setToolTipText("");
        joinSelectedLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinSelectedLobbyButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(" Lobbies                      Players");

        playersInLobby1.setText("0/8");

        playersInLobby2.setText("0/8");

        playersInLobby3.setText("0/8");

        playersInLobby4.setText("0/8");

        playersInLobby5.setText("0/8");

        playersInLobby6.setText("0/8");

        playersInLobby7.setText("0/8");

        playersInLobby8.setText("0/8");

        javax.swing.GroupLayout lobbyPanelLayout = new javax.swing.GroupLayout(lobbyPanel);
        lobbyPanel.setLayout(lobbyPanelLayout);
        lobbyPanelLayout.setHorizontalGroup(
            lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lobbyPanelLayout.createSequentialGroup()
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(joinSelectedLobbyButton))
                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                        .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lobbyPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                                        .addComponent(radioJoinLobby7)
                                        .addGap(27, 27, 27)
                                        .addComponent(playersInLobby7))
                                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                                        .addComponent(radioJoinLobby8)
                                        .addGap(27, 27, 27)
                                        .addComponent(playersInLobby8))
                                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                                        .addComponent(radioJoinLobby5)
                                        .addGap(27, 27, 27)
                                        .addComponent(playersInLobby5))
                                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                                        .addComponent(radioJoinLobby6)
                                        .addGap(27, 27, 27)
                                        .addComponent(playersInLobby6))
                                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                                        .addComponent(radioJoinLobby3)
                                        .addGap(27, 27, 27)
                                        .addComponent(playersInLobby3))
                                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                                        .addComponent(radioJoinLobby4)
                                        .addGap(27, 27, 27)
                                        .addComponent(playersInLobby4))
                                    .addGroup(lobbyPanelLayout.createSequentialGroup()
                                        .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioJoinLobby2)
                                            .addComponent(radioJoinLobby1))
                                        .addGap(27, 27, 27)
                                        .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(playersInLobby1)
                                            .addComponent(playersInLobby2)))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lobbyPanelLayout.setVerticalGroup(
            lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lobbyPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby1)
                    .addComponent(playersInLobby1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playersInLobby2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby3)
                    .addComponent(playersInLobby3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby4)
                    .addComponent(playersInLobby4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby5)
                    .addComponent(playersInLobby5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby6)
                    .addComponent(playersInLobby6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby7)
                    .addComponent(playersInLobby7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lobbyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJoinLobby8)
                    .addComponent(playersInLobby8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(joinSelectedLobbyButton)
                .addContainerGap())
        );

        gameViewPanel.setBackground(new java.awt.Color(140, 140, 140));
        gameViewPanel.setPreferredSize(new java.awt.Dimension(280, 249));

        javax.swing.GroupLayout gameView1Layout = new javax.swing.GroupLayout(gameView1);
        gameView1.setLayout(gameView1Layout);
        gameView1Layout.setHorizontalGroup(
            gameView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        gameView1Layout.setVerticalGroup(
            gameView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gameViewPanelLayout = new javax.swing.GroupLayout(gameViewPanel);
        gameViewPanel.setLayout(gameViewPanelLayout);
        gameViewPanelLayout.setHorizontalGroup(
            gameViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gameViewPanelLayout.setVerticalGroup(
            gameViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout currentViewPanelLayout = new javax.swing.GroupLayout(currentViewPanel);
        currentViewPanel.setLayout(currentViewPanelLayout);
        currentViewPanelLayout.setHorizontalGroup(
            currentViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lobbyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        currentViewPanelLayout.setVerticalGroup(
            currentViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lobbyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenuOption.setText("File");

        fileNewGame.setText("New Game");
        fileNewGame.setActionCommand("fileNewGame");
        fileNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewGameActionPerformed(evt);
            }
        });
        fileMenuOption.add(fileNewGame);
        fileNewGame.getAccessibleContext().setAccessibleName("New Game");

        fileExit.setText("Exit");
        fileExit.setActionCommand("fileExitGame");
        fileMenuOption.add(fileExit);

        jMenuBar1.add(fileMenuOption);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNewGameActionPerformed

    private void joinSelectedLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinSelectedLobbyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinSelectedLobbyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel currentViewPanel;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenu fileMenuOption;
    private javax.swing.JMenuItem fileNewGame;
    private client.GameView gameView1;
    private javax.swing.JPanel gameViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton joinSelectedLobbyButton;
    private javax.swing.JPanel lobbyPanel;
    private javax.swing.JLabel playersInLobby1;
    private javax.swing.JLabel playersInLobby2;
    private javax.swing.JLabel playersInLobby3;
    private javax.swing.JLabel playersInLobby4;
    private javax.swing.JLabel playersInLobby5;
    private javax.swing.JLabel playersInLobby6;
    private javax.swing.JLabel playersInLobby7;
    private javax.swing.JLabel playersInLobby8;
    private javax.swing.JRadioButton radioJoinLobby1;
    private javax.swing.JRadioButton radioJoinLobby2;
    private javax.swing.JRadioButton radioJoinLobby3;
    private javax.swing.JRadioButton radioJoinLobby4;
    private javax.swing.JRadioButton radioJoinLobby5;
    private javax.swing.JRadioButton radioJoinLobby6;
    private javax.swing.JRadioButton radioJoinLobby7;
    private javax.swing.JRadioButton radioJoinLobby8;
    // End of variables declaration//GEN-END:variables
}
